// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PUBLIC_URL = "https://kljojswtseenoqiirveq.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLIC_KEY as string;

export const supabase = createClient<Database>(SUPABASE_PUBLIC_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-v2',
    },
  },
  // Enable realtime subscriptions with optimized settings
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  // Optimize database queries
  db: {
    schema: 'public',
  },
});